### ISSUE TITLE
Please add more feature!

### ISSUE THREAD

**Issue by good777LUCKY** [NycuRO/CoronaAddon-Nukkit#1]
I think this plugin need more feature! For example, when you get Corona at first, there are no symptoms, but as time goes by, symptoms occur and make more worse. What about symptoms like nausea, poison, hunger, and slowness? And when the player is the virus incubation period, if you go near another player, that other player will be infect with a high probability. And after the incubation period, it will be cured, but the player can die with a low probability. This will make the plugin more fun.

**Comment by NycuRO** [comment]
It's an April Fool plugin lmao

**Comment by good777LUCKY** [comment]
Oh...


But can you make it?
